name: Jupyter Notebook Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# ----------------------------------------------------------------------------------------------------------------------

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  test-and-build:
    name: Test Jupyter Notebooks
    runs-on: ubuntu-latest
    container:
      image: "pycram/semantic_world:jazzy"

    steps:

      - name: Checkout semantic_world
        uses: actions/checkout@v3
        with:
          path: "ros/src/semantic_world"
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          submodules: "false"

      # For debugging
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Update semantic_world source files
        run: |
          rm -rf /opt/ros/semantic_world/* 
          cd /opt/ros/semantic_world
          rm -rf .git .github .gitignore .gitmodules .readthedocs.yaml
          cp -r /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/ros/src/semantic_world /opt/ros

      # ----------------------------------------------------------------------------------------------------------------

      - name: Install python dependencies
        run: |
          pip install --upgrade pip --root-user-action=ignore
          source /opt/ros/semantic_world-venv/bin/activate
          cd /opt/ros/semantic_world
          pip install -r requirements.txt
          pip install jupytext treon
          pip install -e .

      # ----------------------------------------------------------------------------------------------------------------
      - name: Convert Notebooks
        run: |
          cd /opt/ros/semantic_world/examples
          source /opt/ros/semantic_world-venv/bin/activate
          python -m jupytext --to notebook *.md

      - name: Run tests
        run: |
          source /opt/ros/overlay_ws/install/setup.bash
          source /opt/ros/semantic_world-venv/bin/activate
          cd /opt/ros/semantic_world/examples/
          python -m treon --thread 1 -v
          rm *.ipynb